// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-mhQN-b5Y7MIHGqNVgXFi-Iwmo7DFANo',
    appId: '1:927062757496:web:ac6020428e868702285d8d',
    messagingSenderId: '927062757496',
    projectId: 'essaieprojet-79165',
    authDomain: 'essaieprojet-79165.firebaseapp.com',
    storageBucket: 'essaieprojet-79165.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_OqPd4DLltxFPUUX-dwRE4Xo1ULvPlnY',
    appId: '1:927062757496:android:2cfa7ffb5a8df106285d8d',
    messagingSenderId: '927062757496',
    projectId: 'essaieprojet-79165',
    storageBucket: 'essaieprojet-79165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDbZKHlidoL1XGfTydKU1CnSG9DmUeaI',
    appId: '1:927062757496:ios:026f4acd27d5de4a285d8d',
    messagingSenderId: '927062757496',
    projectId: 'essaieprojet-79165',
    storageBucket: 'essaieprojet-79165.appspot.com',
    iosBundleId: 'com.example.essaieProjet1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpDbZKHlidoL1XGfTydKU1CnSG9DmUeaI',
    appId: '1:927062757496:ios:026f4acd27d5de4a285d8d',
    messagingSenderId: '927062757496',
    projectId: 'essaieprojet-79165',
    storageBucket: 'essaieprojet-79165.appspot.com',
    iosBundleId: 'com.example.essaieProjet1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-mhQN-b5Y7MIHGqNVgXFi-Iwmo7DFANo',
    appId: '1:927062757496:web:9afe307ab28c1cec285d8d',
    messagingSenderId: '927062757496',
    projectId: 'essaieprojet-79165',
    authDomain: 'essaieprojet-79165.firebaseapp.com',
    storageBucket: 'essaieprojet-79165.appspot.com',
  );
}
